from __future__ import annotations

import hashlib
import pathlib
import re
import time
from dataclasses import dataclass, field
from typing import Any

from ..models import FailureType, Trace
from ..store.sqlite_store import Store

_TEST_FRAMEWORK_TEMPLATE = '''\
"""
Auto-generated regression test for trace {trace_id}.
Generated by TARDIS RegressionTestGenerator at {timestamp}.
DO NOT EDIT MANUALLY — regenerate via `tardis regen-test {trace_id}`.
"""
import json
import pathlib
import sys

import pytest

from tardis.models import Step, StepType, Trace as TardisTrace
from tardis.replay.engine import ReplayEngine
from tardis.autopsy.classifier import Autopsy
from tardis.store.sqlite_store import Store


def _load_trace():
    store = Store()
    trace = store.get_trace("{trace_id}")
    if trace is None:
        raise pytest.skip("Trace {trace_id} not found in store")
    return trace


class TestRegression_{trace_id}:
    """Regression test for replay, autopsy, and failure classification."""

    def test_replay_completes(self):
        trace = _load_trace()
        engine = ReplayEngine(trace.id)
        result = engine.replay()
        assert result is not None
        assert isinstance(result, TardisTrace)

    def test_replay_range_equivalence(self):
        trace = _load_trace()
        engine = ReplayEngine(trace.id)
        result_full = engine.replay(from_idx=0)
        engine2 = ReplayEngine(trace.id)
        result_partial = engine2.replay(from_idx=0, to_idx={total_steps})
        assert len(result_full.steps) >= len(result_partial.steps)

    def test_autopsy_classifies(self):
        trace = _load_trace()
        autopsy = Autopsy(trace)
        ftype, details, confidence = autopsy.classify()
        assert ftype is not None
        assert confidence >= 0.0
        assert isinstance(details, str)

    def test_failure_type_matches(self):
        trace = _load_trace()
        autopsy = Autopsy(trace)
        ftype, details, confidence = autopsy.classify()
{expected_failure_assert}

    def test_critical_step_hashes_present(self):
        trace = _load_trace()
        assert len(trace.steps) > 0
        for step in trace.steps:
            assert step.hash is not None, f"Step {{step.index}} missing hash"

    def test_trace_metadata_preserved(self):
        trace = _load_trace()
        assert trace.id == "{trace_id}"
        assert trace.total_tokens >= 0
        assert trace.total_cost_usd >= 0.0
'''

_ALL_STEPS_CHECK = '''\
    def test_all_steps_types_valid(self):
        trace = _load_trace()
        for step in trace.steps:
            assert isinstance(step.type, StepType)

    def test_step_count(self):
        trace = _load_trace()
        assert len(trace.steps) == {step_count}
'''

_SAFE_IDENTIFIER_RE = re.compile(r"[^a-zA-Z0-9_]")


def _sanitize_identifier(value: str) -> str:
    """Sanitize a string for safe use as a Python identifier in generated code."""
    safe = _SAFE_IDENTIFIER_RE.sub("_", value)
    if not safe or safe[0].isdigit():
        safe = "t_" + safe
    return safe


_FAILURE_TYPE_ASSERT_MAP = {
    FailureType.reasoning_failure: '        assert ftype.value == "reasoning_failure"',
    FailureType.grounding_failure: '        assert ftype.value == "grounding_failure"',
    FailureType.tool_failure: '        assert ftype.value == "tool_failure"',
    FailureType.memory_failure: '        assert ftype.value == "memory_failure"',
    FailureType.environment_drift: '        assert ftype.value == "environment_drift"',
    FailureType.unknown: "        # unknown failure type — no assertion on value",
}


def _generate_test_code(
    trace: Trace,
    output_dir: str,
) -> str:
    raw_id = trace.id
    safe_id = _sanitize_identifier(raw_id)
    timestamp = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    total_steps = len(trace.steps)

    expected_failure_type = trace.failure_type or FailureType.unknown
    expected_failure_assert = _FAILURE_TYPE_ASSERT_MAP.get(
        expected_failure_type,
        "        # failure type not in known set — skipping assertion",
    )
    if expected_failure_type == FailureType.unknown:
        expected_failure_assert = (
            "        # unknown failure type — assertion omitted\n"
            "        pass"
        )

    code = _TEST_FRAMEWORK_TEMPLATE.format(
        trace_id=safe_id,
        timestamp=timestamp,
        total_steps=total_steps,
        step_count=total_steps,
        expected_failure_assert=expected_failure_assert,
    )

    code += _ALL_STEPS_CHECK.format(
        step_count=total_steps,
    )

    error_steps = trace.get_error_steps()
    if error_steps:
        code += f"""
    def test_error_steps_match(self):
        trace = _load_trace()
        errors = trace.get_error_steps()
        assert len(errors) == {len(error_steps)}
"""
        for es in error_steps[:3]:
            safe_err = re.sub(r"[^a-zA-Z0-9_]", "_", es.error_type or "unknown")
            code += f"""\
        assert any("{safe_err}" in (e.error_type or '') for e in errors)
"""

    code += """
    def test_replay_thresholds(self):
        trace = _load_trace()
        duration = trace.get_duration_seconds()
        assert duration >= 0.0
        assert trace.total_tokens >= 0
        assert trace.total_cost_usd >= 0.0
"""
    return code


def _extract_step_hashes(trace: Trace) -> list[str]:
    return [s.hash for s in trace.steps if s.hash is not None]


def _trace_to_test_filename(trace_id: str) -> str:
    safe = re.sub(r"[^a-zA-Z0-9_-]", "_", trace_id)
    return f"regression_test_{safe}.py"


def _generate_test_digest(trace: Trace) -> str:
    hasher = hashlib.sha256()
    hasher.update(trace.id.encode())
    for s in trace.steps:
        hasher.update(f"{s.index}:{s.hash}:{s.type.value}".encode())
    return hasher.hexdigest()[:16]


@dataclass
class TestCase:
    name: str
    source: str
    trace_id: str
    digest: str
    created_at: float = field(default_factory=time.time)
    test_file: str = ""


@dataclass
class RegressionTestSuite:
    output_dir: str = ".tardis/regression_tests"

    def __post_init__(self):
        pathlib.Path(self.output_dir).mkdir(parents=True, exist_ok=True)

    def list_tests(self) -> list[dict[str, Any]]:
        tests = []
        for f in pathlib.Path(self.output_dir).glob("regression_test_*.py"):
            first_line = f.read_text().split("\n")[0] if f.exists() else ""
            trace_id_match = re.search(r"trace ([a-zA-Z0-9_-]+)", first_line)
            tests.append({
                "file": f.name,
                "path": str(f),
                "trace_id": trace_id_match.group(1) if trace_id_match else "unknown",
                "size_bytes": f.stat().st_size,
            })
        return tests

    def remove_test(self, trace_id: str) -> bool:
        pattern = _trace_to_test_filename(trace_id)
        path = pathlib.Path(self.output_dir) / pattern
        if path.exists():
            path.unlink()
            return True
        for f in pathlib.Path(self.output_dir).glob("regression_test_*.py"):
            if trace_id in f.read_text():
                f.unlink()
                return True
        return False

    def get_test_count(self) -> int:
        return len(list(pathlib.Path(self.output_dir).glob("regression_test_*.py")))


class RegressionTestGenerator:
    def __init__(
        self,
        output_dir: str = ".tardis/regression_tests",
        overwrite: bool = False,
    ):
        self.suite = RegressionTestSuite(output_dir=output_dir)
        self.overwrite = overwrite
        self.store = Store()

    def generate_from_trace(self, trace_id: str) -> TestCase:
        trace = self.store.get_trace(trace_id)
        if trace is None:
            raise ValueError(f"Trace {trace_id} not found")
        return self._generate(trace)

    def generate_from_trace_object(self, trace: Trace) -> TestCase:
        return self._generate(trace)

    def _generate(self, trace: Trace) -> TestCase:
        trace_id = trace.id
        filename = _trace_to_test_filename(trace_id)
        dest = pathlib.Path(self.suite.output_dir) / filename

        if dest.exists() and not self.overwrite:
            existing_digest = self._read_digest(dest)
            new_digest = _generate_test_digest(trace)
            if existing_digest == new_digest:
                name = f"TestRegression_{trace_id}"
                return TestCase(
                    name=name,
                    source=dest.read_text(),
                    trace_id=trace_id,
                    digest=new_digest,
                    test_file=str(dest),
                )

        code = _generate_test_code(trace, self.suite.output_dir)
        digest = _generate_test_digest(trace)

        header = (
            f"# digest:{digest}\n"
            f"# trace:{trace_id}\n"
        )
        full_source = header + code

        dest.write_text(full_source, encoding="utf-8")

        name = f"TestRegression_{trace_id}"
        return TestCase(
            name=name,
            source=full_source,
            trace_id=trace_id,
            digest=digest,
            test_file=str(dest),
        )

    def generate_from_all_failed_traces(
        self, limit: int = 50,
    ) -> list[TestCase]:
        traces = self.store.list_traces()[:limit]
        cases = []
        for t_data in traces:
            trace = self.store.get_trace(t_data["id"])
            if trace is None:
                continue
            if trace.success and not trace.get_error_steps():
                continue
            try:
                case = self._generate(trace)
                cases.append(case)
            except Exception:
                continue
        return cases

    def _read_digest(self, path: pathlib.Path) -> str:
        first = path.read_text().split("\n")[0] if path.exists() else ""
        if first.startswith("# digest:"):
            return first.split(":", 1)[1].strip()
        return ""

    def run_tests(self, trace_id: str | None = None) -> dict[str, Any]:
        import subprocess
        import sys

        if trace_id:
            pattern = _trace_to_test_filename(trace_id)
            test_path = pathlib.Path(self.suite.output_dir) / pattern
            if not test_path.exists():
                return {"exit_code": -1, "passed": 0, "failed": 0, "error": "test file not found"}
            result = subprocess.run(
                [sys.executable, "-m", "pytest", str(test_path), "-v", "--tb=short"],
                capture_output=True, text=True, timeout=120,
            )
        else:
            result = subprocess.run(
                [sys.executable, "-m", "pytest", str(self.suite.output_dir), "-v", "--tb=short"],
                capture_output=True, text=True, timeout=120,
            )

        output = result.stdout + result.stderr
        passed = output.count("PASSED")
        failed = output.count("FAILED")
        return {
            "exit_code": result.returncode,
            "passed": passed,
            "failed": failed,
            "output": output[-2000:],
        }
